### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint de signup
POST http://localhost:3003/users/signup 
Content-Type: application/json

{
    "name": "Adriana",
    "email": "adriana@gmail.com",
    "password": "abc123"
}

### Endpoint de login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    
    "email": "adriana@gmail.com",
    "password": "abc123"
}



### Endpoint que cria um post
POST http://localhost:3003/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMzQ3ZWJmLWQ4NmEtNGVhOC1iNzVhLTk1Nzg3ZDljMDkzMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0Mjg1NzksImV4cCI6MTY2MDUxNDk3OX0.g32m0eUmkhedJuxYQ657bBlNJmALjbmMqanuMDmDH8U

{
    "content": "vendo pela enezima vez kkk"
}


### Endpoint que pega todos os posts
GET http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMzQ3ZWJmLWQ4NmEtNGVhOC1iNzVhLTk1Nzg3ZDljMDkzMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0Mjg1NzksImV4cCI6MTY2MDUxNDk3OX0.g32m0eUmkhedJuxYQ657bBlNJmALjbmMqanuMDmDH8U

### Endpoint que deleta post
DELETE http://localhost:3003/posts/bc31ece5-598a-4d47-8efe-94dfe4ea6d1a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMzQ3ZWJmLWQ4NmEtNGVhOC1iNzVhLTk1Nzg3ZDljMDkzMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0Mjg1NzksImV4cCI6MTY2MDUxNDk3OX0.g32m0eUmkhedJuxYQ657bBlNJmALjbmMqanuMDmDH8U

### Endpoint que curte um post
POST http://localhost:3003/posts/201
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMzQ3ZWJmLWQ4NmEtNGVhOC1iNzVhLTk1Nzg3ZDljMDkzMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0Mjg1NzksImV4cCI6MTY2MDUxNDk3OX0.g32m0eUmkhedJuxYQ657bBlNJmALjbmMqanuMDmDH8U

