### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint de signup
POST http://localhost:3003/users/signup 
Content-Type: application/json

{
    "name": "Adriana",
    "email": "adriana@gmail.com",
    "password": "abc123"
}